# Generated by Django 4.2.3 on 2023-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_category_contact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
